version: "3.8"

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 80:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=OtterTech

  ottertech-node-app:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - MYSQL_HOST=db
      - MYSQL_PASS=root
      - MYSQL_DB=OtterTech
      - REDIS_URL=redis://redis
    depends_on:
      - redis

  ottertech-client-app:
    restart: always
    build: ./client
    ports:
      - "8080:8080"
    depends_on:
      - ottertech-node-app
