version: "3.8"

services:
  ottertech-node-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - MYSQL_HOST=db
      - MYSQL_PASS=root
      - MYSQL_DB=OtterTech

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=OtterTech
